"""Days table added

Revision ID: 22dc77c4fcf0
Revises: e2f3af3bcc36
Create Date: 2023-12-01 18:05:11.616856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dc77c4fcf0'
down_revision = 'e2f3af3bcc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_car_days'), ['days'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_days'))
        batch_op.drop_column('days')

    # ### end Alembic commands ###
