"""Groups class added

Revision ID: 30695b80c5cf
Revises: 910302c92d8c
Create Date: 2024-02-06 23:56:42.261046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30695b80c5cf'
down_revision = '910302c92d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('booking_group', 'groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('booking_group', type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
