"""empty message

Revision ID: 3f58530e8f3f
Revises: a7029601195b
Create Date: 2023-11-17 16:48:45.981421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f58530e8f3f'
down_revision = 'a7029601195b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_unique_constraint('_plate_uc', ['plate'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_constraint('_plate_uc', type_='unique')

    # ### end Alembic commands ###
