"""Telephone column added to Contact Class

Revision ID: 3f5cbf2c36b9
Revises: b38bad909377
Create Date: 2024-01-17 15:37:33.263281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5cbf2c36b9'
down_revision = 'b38bad909377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telephone', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contacts_telephone'), ['telephone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_telephone'))
        batch_op.drop_column('telephone')

    # ### end Alembic commands ###
