"""Contactsts class, added columns: town_of_birth, city_of_residence and address

Revision ID: 458d34684d49
Revises: d9c89040cc33
Create Date: 2024-03-27 20:13:38.789364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458d34684d49'
down_revision = 'd9c89040cc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('town_of_birth', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city_of_residence', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_contacts_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_city_of_residence'), ['city_of_residence'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_town_of_birth'), ['town_of_birth'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_town_of_birth'))
        batch_op.drop_index(batch_op.f('ix_contacts_city_of_residence'))
        batch_op.drop_index(batch_op.f('ix_contacts_address'))
        batch_op.drop_column('address')
        batch_op.drop_column('city_of_residence')
        batch_op.drop_column('town_of_birth')

    # ### end Alembic commands ###
