"""Days table removed

Revision ID: 7ca4612c3153
Revises: 22dc77c4fcf0
Create Date: 2023-12-01 18:12:18.064904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca4612c3153'
down_revision = '22dc77c4fcf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index('ix_car_days')
        batch_op.drop_column('days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', sa.INTEGER(), nullable=True))
        batch_op.create_index('ix_car_days', ['days'], unique=False)

    # ### end Alembic commands ###
