"""car table

Revision ID: 7ff79ff8d527
Revises: d7567374f4b3
Create Date: 2023-11-08 18:37:36.721349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff79ff8d527'
down_revision = 'd7567374f4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('plate', sa.String(length=8), nullable=False),
    sa.Column('make', sa.String(length=15), nullable=True),
    sa.Column('model', sa.String(length=15), nullable=True),
    sa.Column('fuel', sa.String(length=8), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('cc', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plate')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_cc'), ['cc'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_fuel'), ['fuel'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_make'), ['make'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_plate'), ['plate'], unique=True)
        batch_op.create_index(batch_op.f('ix_car_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_year'))
        batch_op.drop_index(batch_op.f('ix_car_plate'))
        batch_op.drop_index(batch_op.f('ix_car_model'))
        batch_op.drop_index(batch_op.f('ix_car_make'))
        batch_op.drop_index(batch_op.f('ix_car_fuel'))
        batch_op.drop_index(batch_op.f('ix_car_cc'))

    op.drop_table('car')
    # ### end Alembic commands ###
