"""Add default value to days column in Car model

Revision ID: 8cb08e33dcb9
Revises: 7ca4612c3153
Create Date: 2023-12-01 18:12:41.685589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb08e33dcb9'
down_revision = '7ca4612c3153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_car_days'), ['days'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_days'))
        batch_op.drop_column('days')

    # ### end Alembic commands ###
