"""Renewal_expiry column added

Revision ID: a2290d479c31
Revises: b840a7fe3993
Create Date: 2024-01-26 20:57:32.054929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2290d479c31'
down_revision = 'b840a7fe3993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('renewal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renewal_expiry', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('renewal', schema=None) as batch_op:
        batch_op.drop_column('renewal_expiry')

    # ### end Alembic commands ###
