"""empty message

Revision ID: a7029601195b
Revises: b89f6739c1d2
Create Date: 2023-11-17 16:35:56.848804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7029601195b'
down_revision = 'b89f6739c1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_constraint('unique_plate_user', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_plate_user', ['plate', 'user_id'])

    # ### end Alembic commands ###
