"""Insurance, MOT and Tax columns added to Car Class

Revision ID: b38bad909377
Revises: 5a9f2f0c0a45
Create Date: 2024-01-11 19:13:41.141378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38bad909377'
down_revision = '5a9f2f0c0a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_cost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('insurance_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('insurance_expiry_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('mot_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mot_expiry_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('road_tax_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('road_tax_expiry_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_car_car_cost'), ['car_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_insurance_cost'), ['insurance_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_mot_cost'), ['mot_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_road_tax_cost'), ['road_tax_cost'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_road_tax_cost'))
        batch_op.drop_index(batch_op.f('ix_car_mot_cost'))
        batch_op.drop_index(batch_op.f('ix_car_insurance_cost'))
        batch_op.drop_index(batch_op.f('ix_car_car_cost'))
        batch_op.drop_column('road_tax_expiry_date')
        batch_op.drop_column('road_tax_cost')
        batch_op.drop_column('mot_expiry_date')
        batch_op.drop_column('mot_cost')
        batch_op.drop_column('insurance_expiry_date')
        batch_op.drop_column('insurance_cost')
        batch_op.drop_column('car_cost')

    # ### end Alembic commands ###
