"""Plate Bug Fixed

Revision ID: b89f6739c1d2
Revises: b095b7fc190f
Create Date: 2023-11-16 18:42:01.523781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89f6739c1d2'
down_revision = 'b095b7fc190f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index('ix_car_plate')
        batch_op.create_index(batch_op.f('ix_car_plate'), ['plate'], unique=False)
        batch_op.create_unique_constraint('unique_plate_user', ['plate', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_constraint('unique_plate_user', type_='unique')
        batch_op.drop_index(batch_op.f('ix_car_plate'))
        batch_op.create_index('ix_car_plate', ['plate'], unique=False)

    # ### end Alembic commands ###
