"""Money column added

Revision ID: ba4defa9a3b5
Revises: 8cb08e33dcb9
Create Date: 2023-12-01 20:14:24.221693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4defa9a3b5'
down_revision = '8cb08e33dcb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('money', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_car_money'), ['money'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_money'))
        batch_op.drop_column('money')

    # ### end Alembic commands ###
