"""Contacts class, driver_licence_n is now a string

Revision ID: d9c89040cc33
Revises: 2d10b752c2dd
Create Date: 2024-03-27 19:48:13.434092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9c89040cc33'
down_revision = '2d10b752c2dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('driver_licence_n',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('driver_licence_n',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
