"""Added note column to Booking

Revision ID: e2f3af3bcc36
Revises: 07dfa2cd4b87
Create Date: 2023-11-18 19:03:04.140938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f3af3bcc36'
down_revision = '07dfa2cd4b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=160), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
