"""empty message

Revision ID: e6756aac58b6
Revises: 
Create Date: 2024-03-15 17:28:38.408094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6756aac58b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=1), nullable=True),
    sa.Column('measurement_unit', sa.String(length=5), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('car',
    sa.Column('plate', sa.String(length=8), nullable=False),
    sa.Column('make', sa.String(length=15), nullable=True),
    sa.Column('model', sa.String(length=15), nullable=True),
    sa.Column('fuel', sa.String(length=8), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('cc', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('car_cost', sa.Integer(), nullable=True),
    sa.Column('insurance_cost', sa.Float(), nullable=True),
    sa.Column('insurance_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('mot_cost', sa.Float(), nullable=True),
    sa.Column('mot_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('road_tax_cost', sa.Float(), nullable=True),
    sa.Column('road_tax_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('km', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plate')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_car_cost'), ['car_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_cc'), ['cc'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_days'), ['days'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_fuel'), ['fuel'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_insurance_cost'), ['insurance_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_km'), ['km'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_make'), ['make'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_money'), ['money'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_mot_cost'), ['mot_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_plate'), ['plate'], unique=True)
        batch_op.create_index(batch_op.f('ix_car_road_tax_cost'), ['road_tax_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_year'), ['year'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('driver_licence_n', sa.Integer(), nullable=True),
    sa.Column('dob', sa.String(length=8), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('money_spent', sa.Integer(), nullable=True),
    sa.Column('rented_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='contacts_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_dob'), ['dob'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_driver_licence_n'), ['driver_licence_n'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_money_spent'), ['money_spent'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_rented_days'), ['rented_days'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_telephone'), ['telephone'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('bookings_number', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_bookings_number'), ['bookings_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_money'), ['money'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_telephone'), ['telephone'], unique=False)

    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('car_plate', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=160), nullable=True),
    sa.Column('money', sa.Integer(), nullable=True),
    sa.Column('km', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_plate'], ['car.plate'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='booking_contacts_id'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='booking_group'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_km'), ['km'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_money'), ['money'], unique=False)

    op.create_table('renewal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.String(length=8), nullable=True),
    sa.Column('renewal_type', sa.String(length=50), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('renewal_expiry', sa.Date(), nullable=True),
    sa.Column('renewal_cost', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.plate'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('renewal')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_money'))
        batch_op.drop_index(batch_op.f('ix_booking_km'))

    op.drop_table('booking')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_telephone'))
        batch_op.drop_index(batch_op.f('ix_groups_name'))
        batch_op.drop_index(batch_op.f('ix_groups_money'))
        batch_op.drop_index(batch_op.f('ix_groups_bookings_number'))

    op.drop_table('groups')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_telephone'))
        batch_op.drop_index(batch_op.f('ix_contacts_rented_days'))
        batch_op.drop_index(batch_op.f('ix_contacts_money_spent'))
        batch_op.drop_index(batch_op.f('ix_contacts_full_name'))
        batch_op.drop_index(batch_op.f('ix_contacts_driver_licence_n'))
        batch_op.drop_index(batch_op.f('ix_contacts_dob'))

    op.drop_table('contacts')
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_year'))
        batch_op.drop_index(batch_op.f('ix_car_road_tax_cost'))
        batch_op.drop_index(batch_op.f('ix_car_plate'))
        batch_op.drop_index(batch_op.f('ix_car_mot_cost'))
        batch_op.drop_index(batch_op.f('ix_car_money'))
        batch_op.drop_index(batch_op.f('ix_car_model'))
        batch_op.drop_index(batch_op.f('ix_car_make'))
        batch_op.drop_index(batch_op.f('ix_car_km'))
        batch_op.drop_index(batch_op.f('ix_car_insurance_cost'))
        batch_op.drop_index(batch_op.f('ix_car_fuel'))
        batch_op.drop_index(batch_op.f('ix_car_days'))
        batch_op.drop_index(batch_op.f('ix_car_cc'))
        batch_op.drop_index(batch_op.f('ix_car_car_cost'))

    op.drop_table('car')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
