"""Km added to Car and Booking

Revision ID: f0a839fc555a
Revises: a2290d479c31
Create Date: 2024-02-02 13:05:43.766236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a839fc555a'
down_revision = 'a2290d479c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('km', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_booking_km'), ['km'], unique=False)

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('km', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_car_km'), ['km'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_km'))
        batch_op.drop_column('km')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_km'))
        batch_op.drop_column('km')

    # ### end Alembic commands ###
