"""Money_spent and Rented_days columns added to Contacts Class

Revision ID: f169e04f7b84
Revises: ec136b3b713c
Create Date: 2024-01-19 14:18:25.202167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f169e04f7b84'
down_revision = 'ec136b3b713c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('money_spent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rented_days', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contacts_money_spent'), ['money_spent'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_rented_days'), ['rented_days'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_rented_days'))
        batch_op.drop_index(batch_op.f('ix_contacts_money_spent'))
        batch_op.drop_column('rented_days')
        batch_op.drop_column('money_spent')

    # ### end Alembic commands ###
